bLength: 4                     # integer
minAFactor: 1                    # double, should be >= 1 and <= maxAFactor
maxAFactor: 3                   # double 
aStep: 1                         # integer 
aLowercaseProbability: 0.99      # double 
bLowercaseProbability: 0.01      # double 
