bLength: 4                       # integer, b string length
minAFactor: 1                    # double, should be >= 1 and <= maxAFactor - how min many times is a longer than b
maxAFactor: 5                    # double, - how max many times is a longer than b
aStep: 1                         # integer - step, from b to maxA
aLowercaseProbability: 0.99      # double - probability, that extra character in "a" string will be lowercase
bLowercaseProbability: 0.01      # double - probability, that single character in "b" string is going to be lowercae
casesToGenerate: 10              # integer - cases to generate